version: '3.4'

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./vhost:/etc/nginx/conf.d
      - ../Code:/var/www/html
    links:
      - phpfpm
 #     - phpfpm2

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: qazasdedc123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/mysql.conf.d
      - ./mysql/data/:/var/mysql

  redis:
    image: redis:3.2.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./influxDB/data:/data

  mongodb:
    image: mongo:3.2
    ports:
      - "27017:27017"

#  python:
#    image: python:v3
#    ports:
#      - "5000:5000"
#    volumes:
#      - ../Code/Python:/var/www
#      - ./python3/supervisord:/etc/supervisor/conf.d
#    links:
#      - mysql
#      - redis
#    command: '/usr/local/bin/gunicorn  -c gunicorn.py server:app'

  phpfpm:
    image: phpswoole:v1.0
    volumes:
      - ../Code:/var/www/html
      - ./php-fpm7.2/queue:/etc/supervisor/conf.d
      - ./php-fpm7.2/kuozan:/home/kuozan
      - ./php-fpm7.2/phpini:/usr/local/etc/php
    ports:
      - "9000"
      - "9501:9501"
      - "18308:18308"
      - "18307:18307"
      - "18306:18306"
      - "9500:9500"
      - "2347:2347"
    links:
      - mysql
      - mongodb
    extra_hosts:
      - "github.com:13.229.188.59"
      - "github.global.ssl.fastly.net:93.46.8.89"

 
 
# gitlab-runner
#  gitlab-runner:
#    image: gitlab/gitlab-runner
#    restart: always
#    hostname: gitlab-runner
#    container_name: gitlab-runner
#    volumes:
