version: '3.4'

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./vhost:/etc/nginx/conf.d
      - ../Code:/var/www/html
    links:
      - phpfpm

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: qazasdedc123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/etc/mysql/mysql.conf.d

  redis:
    image: redis:3.2.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./influxDB/data:/data

  mongodb:
    image: mongo:3.2
    ports:
      - "27017:27017"

  # perlwx:
  #   image: perl:v1.0
  #   volumes:
  #     - ../Code/My/perlWx:/var/www
  #   command: |
  #     /bin/bash -c "
  #       perl /var/www/index.pl
  #     "

  # influxdb:
  #   image: influxdb:v1.0
  #   ports: 
  #     - "8086:8086"
  #     - "8083:8083"

  # cadvisor:
  #   image: cadvisor:v1.0
  #   ports:
  #     - "8082:8080"
  #   storage_driver:
  #     - "influxdb"
  #   storage_driver_db:
  #     - "docker_db"
  #   storage_driver_host:
  #     - "influxdb:8086"

  phpfpm:
    image: php7.2:v1.0
    volumes:
      - ../Code:/var/www/html
      - ../paycert:/home/paycert
      - ./php-fpm7.2/queue:/etc/supervisor/conf.d
    ports:
      - "9000"
      - "9501:9501"
    links:
      - mysql
      - mongodb 
#    command: supervisord -c /etc/supervisor/conf.d/tpqueue.conf
