concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "citest"
  url = "https://gitlab.com/"
  token = "JxLQB66soGfxPyowUMDk"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "rastasheep/ubuntu-sshd:12.04"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
